# -*- coding: utf-8 -*-
"""Sprint 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129xKiFR650hAUHebFrlDzjbCP8Pw5vnM

As a professor, I want to be able to select different combinations of factors and calculate the information ratio for each combination so I can see how factors perform together.

Import necessary libraries
"""

import pandas as pd
import numpy as np
from scipy import stats
from google.colab import drive
from google.colab import files

"""Read and process data file"""

excelData = pd.read_excel("FR2000AnnualQuantDataFORRETURNSIMULATION.xlsx")

#preprocess
excelData = excelData.dropna()

"""Factor selection"""

# Define possible factors with numbers
factors = {
    1: '12-Mo Momentum %',
    2: '6-Mo Momentum %',
    3: '1-Mo Momentum %',
    4: '1-Yr Price Vol %',
    5: 'Accruals/Assets',
    6: 'ROA %',
    7: '1-Yr Asset Growth %',
    8: '1-Yr CapEX Growth %',
    9: 'Book/Price',
    10: "Next-Year's Return %",
    11: "Next-Year's Active Return %",
    12: 'ROE using 9/30 Data',
    13: 'ROA using 9/30 Data',
    14: 'Price to Book Using 9/30 Data'
}

# Display numbered factors
print("Available factors:")
for num, factor in factors.items():
    print(f"{num}: {factor}")

# Get the number of factors to use
factor_number = int(input("How many factors do you want to use? "))

# Get user-selected factors by number
factor_set = []
for i in range(factor_number):
    while True:
        try:
            user_choice = int(input(f"Enter factor number ({i+1}/{factor_number}): "))
            if user_choice in factors:
                factor_set.append(factors[user_choice])
                break
            else:
                print("Invalid number. Please enter a number from the list.")
        except ValueError:
            print("Invalid input. Please enter a number.")

print("\nSelected factors:")
for factor in factor_set:
    print(factor)

"""Construct Portfolio"""

